# config.yaml
# NEVER commit this file to version control or share it
# This is for REAL Binance mainnet (live trading)

binance:
  api_key:     "9ORkgAY8HXA0w51LUTAHkD9J5C7y4J9hrXX2NUtGuXbWzSePHlTW3daLPpdytvvM"
  api_secret:  "iDHclDBFyQVjGXVOhnwIFMf2NEsx1wfZVJ0ksM1SAOhgb0RJtgDDXP2grfLMGmQr"



trading:
  symbol:             "XRPUSDT"           # change to SOLUSDT, ETHUSDT, etc. if desired
  leverage:           5                   # start low (1–20 recommended for testing)
  margin_type:        "ISOLATED"          # or "CROSSED"
  default_quantity:   5             # very small – adjust according to symbol precision


telegram:
  token: 7904776370:AAFB77L9ninv5r0wP_g4vTTkzLYO6-7bdY0
